unit Unit2;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  jpeg, ExtCtrls, VCLBase, EPLabels;

type
  TForm2 = class(TForm)
    Panel1: TPanel;
    Image1: TImage;
    epWaveLabel1: TepWaveLabel;
    epWaveLabel2: TepWaveLabel;
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form2: TForm2;

implementation

{$R *.DFM}

end.
